### PR TITLE
Add http --status-port for encryptor/updater

### PR DESCRIPTION
**Pull request by dramdass**
Default port is 8000 but allow specifying custom port. The
encryptor knows which port to use because we put it in userdata.

### CODE REVIEW

**Comment by dramdass** [comment]
This isn't ready to merge yet until the encryptor change is in

**Comment by bonzotronix** [comment]
These changes LGTM.  Do we usually re-submit a new PR with squashed changes?

BTW, our long arg lists to functions like encrypt() are getting way out of hand.  I suspect we'll need to pass around Config objects or something like that soon.

**Comment by dramdass** [comment]
@bonzotronix I'll resubmit. Small issue still needed to be resolved here is some ports cannot be specified  because they are already used by other services. I'll add that validation check and resubmit.

**Comment by dramdass** [comment]
Closed since it is tracked in another PR

**Pull request closed without merging**
