### PR TITLE
Explictly add public IP to all instances.

### PR DESCRIPTION
**Pull request by gdmen**

### CODE REVIEW

**Comment by bburtin** [comment]
Can you please update your commit description so that we remember why you're making this change?

**Comment by bburtin** [comment]
Now that I think about it, it would probably be even better to put the reasoning in the comments in the code.

**Comment by gdmen** [comment]
Shelving this for now unless it turns out we really need it.

**Comment by bobveznat** [comment]
I think most people will want to launch private instances in private subnets with only private IPs. Having public IPs show up on instances will be pretty scary for a lot of people.

Given that this idea is being shelved its kind of no big deal. Before doing something like this in the future I think we should discuss it more.

**Comment by gdmen** [comment]
Yeah, that's the reason I closed it. And the only case this would improve would be when customers have a subnet that they don't have local access to and that defaults to no public IP.

**Pull request closed without merging**
