### PR TITLE
Add --network option to update and encrypt gce

### PR DESCRIPTION
**Pull request by robertabbott**
Allows user to specify a non-default network
to launch encryptor instances in

Testing: encrypted and updated gce images

### CODE REVIEW

**Comment by krishnanrs** [comment]
Where are we validating if the network entered is valid? Or are we just letting GCE APIs error out if that happens to be the case?

**Comment by robertabbott** [comment]
we don't check that the network is valid. It will fail when launching the encryptor if the network is invalid

**Comment by bburtin** [comment]
Bobby's approach should be ok, as long as we fail quickly, we don't show a traceback, and the error message is clear.  If this isn't the case, we should be proactive about validating user input.

**Comment by krishnanrs** [comment]
lgtm

**Pull request merged**
